apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wikimedia.fullname" . }}-mariadb-secret
  namespace: {{ .Release.namespace }}
data:
  dbname: {{ .Values.secrets.dbname }}
  dbpassword: {{ .Values.secrets.dbpassword }}
  dbrootpassword: {{ .Values.secrets.dbrootpassword }}
  dbuser: {{ .Values.secrets.dbuser }}

